# gmake
# This file is automatically generated for client.mk.
# Do not edit. Edit /home/robert/tinderbox/release-SeaMonkey-1.1/mozconfig instead.
# To create a new .mozconfig file, you can visit,
#   http://webtools.mozilla.org/build/config.cgi

# PATH=/home/robert/bin:/usr/local/bin:/usr/bin:/usr/X11R6/bin:/bin:/usr/games:/opt/gnome/bin:/home/robert/tinderbox/release-SeaMonkey-1.1/Linux_2.4.21-303-default_Clobber/mozilla/../build//dist/bin
MOZ_OBJDIR=../build
MOZ_CO_PROJECT=suite
# --enable-application=suite is used by configure (not client.mk)
MOZILLA_OFFICIAL=1
BUILD_OFFICIAL=1
# --disable-tests is used by configure (not client.mk)
# --enable-extensions=default is used by configure (not client.mk)
# --without-system-nspr is used by configure (not client.mk)
# --without-system-jpeg is used by configure (not client.mk)
# --without-system-zlib is used by configure (not client.mk)
# --without-system-png is used by configure (not client.mk)
# --disable-debug is used by configure (not client.mk)
# --enable-optimize=-O2 -gstabs+ is used by configure (not client.mk)
# --enable-crypto is used by configure (not client.mk)
# --disable-elf-dynstr-gc is used by configure (not client.mk)
# --enable-strip is used by configure (not client.mk)
# --enable-default-toolkit=gtk2 is used by configure (not client.mk)
# --enable-xft is used by configure (not client.mk)
# --disable-freetype2 is used by configure (not client.mk)
# --disable-xprint is used by configure (not client.mk)
# --enable-svg is used by configure (not client.mk)
# --enable-svg-renderer-cairo is used by configure (not client.mk)
# --enable-canvas is used by configure (not client.mk)
